//
//  taycan_core_error.c
//  Taycan.Swift
//
//  Created by Mengyu Li on 2019-05-07.
//  Copyright © 2019 L1MeN9Yu. All rights reserved.
//

#include "taycan_core_consts.h"
#include <lmdb/lmdb.h>

// Error Code
const int TAYCAN_KEYEXIST = MDB_KEYEXIST;
const int TAYCAN_NOTFOUND = MDB_NOTFOUND;
const int TAYCAN_PAGE_NOTFOUND = MDB_PAGE_NOTFOUND;
const int TAYCAN_CORRUPTED = MDB_CORRUPTED;
const int TAYCAN_PANIC = MDB_PANIC;
const int TAYCAN_VERSION_MISMATCH = MDB_VERSION_MISMATCH;
const int TAYCAN_INVALID = MDB_INVALID;
const int TAYCAN_MAP_FULL = MDB_MAP_FULL;
const int TAYCAN_DBS_FULL = MDB_DBS_FULL;
const int TAYCAN_READERS_FULL = MDB_READERS_FULL;
const int TAYCAN_TLS_FULL = MDB_TLS_FULL;
const int TAYCAN_TXN_FULL = MDB_TXN_FULL;
const int TAYCAN_CURSOR_FULL = MDB_CURSOR_FULL;
const int TAYCAN_PAGE_FULL = MDB_PAGE_FULL;
const int TAYCAN_MAP_RESIZED = MDB_MAP_RESIZED;
const int TAYCAN_INCOMPATIBLE = MDB_INCOMPATIBLE;
const int TAYCAN_BAD_RSLOT = MDB_BAD_RSLOT;
const int TAYCAN_BAD_TXN = MDB_BAD_TXN;
const int TAYCAN_BAD_VALSIZE = MDB_BAD_VALSIZE;
const int TAYCAN_BAD_DBI = MDB_BAD_DBI;

// Environment Flags
const int TAYCAN_FIXEDMAP = MDB_FIXEDMAP;
const int TAYCAN_NOSUBDIR = MDB_NOSUBDIR;
const int TAYCAN_NOSYNC = MDB_NOSYNC;
const int TAYCAN_RDONLY = MDB_RDONLY;
const int TAYCAN_NOMETASYNC = MDB_NOMETASYNC;
const int TAYCAN_WRITEMAP = MDB_WRITEMAP;
const int TAYCAN_MAPASYNC = MDB_MAPASYNC;
const int TAYCAN_NOTLS = MDB_NOTLS;
const int TAYCAN_NOLOCK = MDB_NOLOCK;
const int TAYCAN_NORDAHEAD = MDB_NORDAHEAD;
const int TAYCAN_NOMEMINIT = MDB_NOMEMINIT;
const int TAYCAN_CREATE = MDB_CREATE;
const int TAYCAN_NODUPDATA = MDB_NODUPDATA;
const int TAYCAN_NOOVERWRITE = MDB_NOOVERWRITE;
const int TAYCAN_RESERVE = MDB_RESERVE;
const int TAYCAN_APPEND = MDB_APPEND;
const int TAYCAN_APPENDDUP = MDB_APPENDDUP;